green_schema = types.StructType([
    StructField(VendorID,LongType,true),
    StructField(lpep_pickup_datetime,TimestampType,true),
    StructField(lpep_dropoff_datetime,TimestampType,true),
    StructField(store_and_fwd_flag,StringType,true),
    StructField(RatecodeID,DoubleType,true),
    StructField(PULocationID,LongType,true),
    StructField(DOLocationID,LongType,true),
    StructField(passenger_count,DoubleType,true),
    StructField(trip_distance,DoubleType,true),
    StructField(fare_amount,DoubleType,true),
    StructField(extra,DoubleType,true),
    StructField(mta_tax,DoubleType,true),
    StructField(tip_amount,DoubleType,true),
    StructField(tolls_amount,DoubleType,true),
    StructField(ehail_fee,IntegerType,true),
    StructField(improvement_surcharge,DoubleType,true),
    StructField(total_amount,DoubleType,true),
    StructField(payment_type,DoubleType,true),
    StructField(trip_type,DoubleType,true),
    StructField(congestion_surcharge,DoubleType,true)
])

#ini bukan yellow keknya deh
yellow_schema = types.StructType([
    types.StructField("VendorID", types.IntegerType(), True),
    types.StructField("lpep_pickup_datetime", types.TimestampType(), True),
    types.StructField("lpep_dropoff_datetime", types.TimestampType(), True),
    types.StructField("store_and_fwd_flag", types.StringType(), True),
    types.StructField("RatecodeID", types.IntegerType(), True),
    types.StructField("PULocationID", types.IntegerType(), True),
    types.StructField("DOLocationID", types.IntegerType(), True),
    types.StructField("passenger_count", types.IntegerType(), True),
    types.StructField("trip_distance", types.DoubleType(), True),
    types.StructField("fare_amount", types.DoubleType(), True),
    types.StructField("extra", types.DoubleType(), True),
    types.StructField("mta_tax", types.DoubleType(), True),
    types.StructField("tip_amount", types.DoubleType(), True),
    types.StructField("tolls_amount", types.DoubleType(), True),
    types.StructField("ehail_fee", types.DoubleType(), True),
    types.StructField("improvement_surcharge", types.DoubleType(), True),
    types.StructField("total_amount", types.DoubleType(), True),
    types.StructField("payment_type", types.IntegerType(), True),
    types.StructField("trip_type", types.IntegerType(), True),
    types.StructField("congestion_surcharge", types.DoubleType(), True)
])